export const productos = [
  {
    id: 1,
    nombre: "Mochila Andeer",
    descripcion: "Increíble mochila para ir a la escuela, con capacidad para libros, ropa, lunch y compartimentos para todos tus útiles escolares.",
    precio: 599,
    oferta: 499,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "azul",
    categoria: "mochilas",
    imagenes: ["m9.jpg"],
    colores: ["ginda"],
    tallas: ["Única"]
  },
  {
    id: 2,
    nombre: "Mochila Bloevia",
    descripcion: "Una mochila con aspecto retro, con diferentes espacios para que tengas una mejor una organización interna de tus cosas. Con compartimientos para útiles y accesorios.",
    precio: 399,
    oferta: null,
    existencia: 2,
    cantidad: 2,
    colorSeleccionado: "gris",
    categoria: "mochilas",
    imagenes: ["m8.jpg", "m10.jpg"],
    colores: ["gris", "azul jeans"]
  },
  {
    id: 3,
    nombre: "Mochila de temporada",
    descripcion: "Una mochila pensada para los niños del hogar. Con imágenes de sus personajes favoritos: Iron Man, Mario Bros y Merlina. Excelente opción para el regreso a clases y un precio muy conveniente para los papás.",
    precio: 500,
    oferta: 450,
    existencia: 3,
    cantidad: 2,
    colorSeleccionado: "azul",
    categoria: "mochilas",
    imagenes: ["m4.jpg","m5.jpg","m6.jpg"],
    colores: ["azul", "dorado", "morado"]
  },
  {
    id: 4,
    nombre: "Maleta para ejercicio Pink",
    descripcion: "Esta maleta está pensada para el ejercicio diario y para las personas que gustan de él. Con su estructura alargada logra un máximo de capacidad ideal para tu ropa deportiva y comodidad al transportarla.",
    precio: 600,
    oferta: 500,
    existencia: 3,
    cantidad: 2,
    colorSeleccionado: "morado",
    categoria: "maletas",
    imagenes: ["m2.jpg","m1.jpg","m3.jpg"],
    colores: ["amarillo", "negro", "morado"]
  },
  {
    id: 5,
    nombre: "Bolsa de mano",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b.jpg"],
    colores: ["blanco"]
  },
  {
    id: 6,
    nombre: "Bolsa de mano Ralph Lauren",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b1.jpg"],
    colores: ["blanco"]
  },
  {
    id: 7,
    nombre: "Bolsa de mano",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b2.jpg"],
    colores: ["blanco"]
  },
  {
    id: 8,
    nombre: "Bolsa de mano DkNY",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b3.jpg"],
    colores: ["blanco"]
  },
  {
    id: 9,
    nombre: "Bolsa de mano Ralph Lauren",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b4.jpg"],
    colores: ["blanco"]
  },
  {
    id: 10,
    nombre: "Bolsa de mano Steve Madden",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b5.jpg"],
    colores: ["blanco"]
  },
  {
    id: 11,
    nombre: "Bolsa de mano Tommy Hilfigher",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b7.jpg"],
    colores: ["blanco"]
  },
  {
    id: 12,
    nombre: "Bolsa de mano Aldo",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b8.jpg"],
    colores: ["blanco"]
  },
  {
    id: 13,
    nombre: "Bolsa de mano",
    descripcion: "Una mochila pensada en que realices tus actividades diarias, idónea para el gimnasio y la escuela..",
    precio: 700,
    oferta: 500,
    existencia: 1,
    cantidad: 1,
    colorSeleccionado: "blanco",
    categoria: "bolsas",
    imagenes: ["b9.jpg"],
    colores: ["blanco"]
  },
];
  